// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SortFlow.Infrastructure.Data;

#nullable disable

namespace SortFlow.Infrastructure.Migrations
{
    [DbContext(typeof(SortFlowDbContext))]
    partial class SortFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SortFlow.Domain.Entities.AppSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AddressMismatchProbability")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DamagedLabelProbability")
                        .HasColumnType("double precision");

                    b.Property<int>("DashboardWindowMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("EnableModules")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("GeneratorRatePerSecond")
                        .HasColumnType("double precision");

                    b.Property<double>("InvalidPostalProbability")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("SortFlow.Domain.Entities.SortingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("ZoneId");

                    b.ToTable("SortingEvents");
                });

            modelBuilder.Entity("SortFlow.Domain.Entities.SortingException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("ExceptionType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SortingEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExceptionType");

                    b.HasIndex("SortingEventId")
                        .IsUnique();

                    b.HasIndex("Timestamp");

                    b.ToTable("SortingExceptions");
                });

            modelBuilder.Entity("SortFlow.Domain.Entities.SortingStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("SortingStations");
                });

            modelBuilder.Entity("SortFlow.Domain.Entities.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("SortFlow.Domain.Entities.SortingEvent", b =>
                {
                    b.HasOne("SortFlow.Domain.Entities.SortingStation", "SortingStation")
                        .WithMany("SortingEvents")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SortFlow.Domain.Entities.Zone", "Zone")
                        .WithMany("SortingEvents")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SortingStation");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("SortFlow.Domain.Entities.SortingException", b =>
                {
                    b.HasOne("SortFlow.Domain.Entities.SortingEvent", "SortingEvent")
                        .WithOne("SortingException")
                        .HasForeignKey("SortFlow.Domain.Entities.SortingException", "SortingEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SortingEvent");
                });

            modelBuilder.Entity("SortFlow.Domain.Entities.SortingStation", b =>
                {
                    b.HasOne("SortFlow.Domain.Entities.Zone", "Zone")
                        .WithMany("SortingStations")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("SortFlow.Domain.Entities.SortingEvent", b =>
                {
                    b.Navigation("SortingException");
                });

            modelBuilder.Entity("SortFlow.Domain.Entities.SortingStation", b =>
                {
                    b.Navigation("SortingEvents");
                });

            modelBuilder.Entity("SortFlow.Domain.Entities.Zone", b =>
                {
                    b.Navigation("SortingEvents");

                    b.Navigation("SortingStations");
                });
#pragma warning restore 612, 618
        }
    }
}
